.\"     Title: atlas-shell-tools
.\"    Author: Lucas Cram
.\"    Source: atlas-shell-tools 0.0.1
.\"  Language: English
.\"
.TH "ATLAS-SHELL-TOOLS" "7" "1 December 2018" "atlas\-shell\-tools 0\&.0\&.1" "Atlas Shell Tools Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH "NAME"
.sp
atlas\-shell\-tools \-\- A command line toolkit for Atlas and related projects

.SH "SYNOPSIS"
*

.SH "DESCRIPTION"
The Atlas Shell Tools are a command line toolkit for running commands defined
in Atlas and related projects. The main tool for running commands is
\fBatlas\fR(1), and the installation can be configured with \fBatlas\-config\fR(1)
and its various subcommands.

.SH "MANUAL PAGES"
.RS 4

\fBatlas\fR(1)
.RS 4
Run an Atlas Shell Tools command
.RE

\fBatlas\-config\fR(1)
.RS 4
Configure the Atlas Shell Tools installation
.RE

\fBatlas\-config\-activate\fR(1)
.RS 4
Activate an installed module
.RE

\fBatlas\-config\-deactivate\fR(1)
.RS 4
Deactivate an installed module
.RE

\fBatlas\-config\-install\fR(1)
.RS 4
Install a new Atlas Shell Tools module from a local JAR
.RE

\fBatlas\-config\-list\fR(1)
.RS 4
List installed modules and module statuses
.RE

\fBatlas\-config\-log\fR(1)
.RS 4
Check or set log parameters
.RE

\fBatlas\-config\-preset\fR(1)
.RS 4
Create and manage Atlas Shell Tools command presets
.RE

\fBatlas\-config\-repo\fR(1)
.RS 4
Register and manage Atlas Shell Tools repositories
.RE

\fBatlas\-config\-reset\fR(1)
.RS 4
Reset the installation
.RE

\fBatlas\-config\-sync\fR(1)
.RS 4
Refresh the installation based on the active module
.RE

\fBatlas\-config\-uninstall\fR(1)
.RS 4
Uninstall Atlas Shell Tools module(s)
.RE

\fBatlas\-config\-update\fR(1)
.RS 4
Update the Atlas Shell Tools core toolkit
.RE

\fBatlas\-plumbing\fR(5)
.RS 4
Details about how Atlas Shell Tools stores program data
.RE

\fBatlas\-cli\fR(7)
.RS 4
Atlas Shell Tools command line interface and conventions
.RE

\fBatlas\-cookbook\fR(7)
.RS 4
Atlas Shell Tools command cookbook
.RE

\fBatlas\-glossary\fR(7)
.RS 4
A glossary of Atlas Shell Tools terms and concepts
.RE

\fBatlas\-presets\fR(7)
.RS 4
Atlas Shell Tools preset interface
.RE

.RE


.SH "ATLAS SHELL TOOLS"
.sp
Part of the \fBatlas\-shell\-tools\fR(7) suite
