.\"     Title: atlas-cli
.\"    Author: Lucas Cram
.\"    Source: atlas-shell-tools 0.0.1
.\"  Language: English
.\"
.TH "ATLAS-CLI" "7" "1 December 2018" "atlas\-shell\-tools 0\&.0\&.1" "Atlas Shell Tools Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH "NAME"
.sp
atlas\-cli \-\- Atlas Shell Tools command line interface and conventions

.SH "SYNOPSIS"
*

.SH "DESCRIPTION"
.sp
\fBatlas\-shell\-tools\fR(7) makes use of various command line conventions and
utilities to provide a comprehensive user experience.

The \fBShells\fR section discusses the various shells supported by \fBatlas\-shell\-tools\fR(7).

The \fBOptions\fR section explains the various ways \fBatlas\-shell\-tools\fR(7) parses
command line options.

The \fBTAB Complete\fR section shows the various ways that TAB completions can make command
line interaction easier.

.SH "SHELLS"
.sp
While \fBatlas\-shell\-tools\fR(7) is compatible with any command shell, \fBbash\fR(1) and
\fBzsh\fR(1) users can take advantage of both the quick installation scripts and advanced TAB
completion features.

\fBzsh\fR(1) provides the best experience

For \fBbash\fR(1) users, note that while \fBatlas\-shell\-tools\fR(7) works best with \fBbash\fR(1)
version 4, version 3 can still utilize the full TAB complete feature set.

.SH "OPTIONS"
.sp
TODO

.SH "TAB COMPLETE"
.sp
TODO

.SH "ATLAS SHELL TOOLS"
.sp
Part of the \fBatlas\-shell\-tools\fR(7) suite
