.\"     Title: atlas-shell-tools
.\"    Author: Lucas Cram
.\"    Source: atlas-shell-tools 0.0.1
.\"  Language: English
.\"
.TH "ATLAS-SHELL-TOOLS" "7" "1 December 2018" "atlas\-shell\-tools 1\&.0\&.0" "Atlas Shell Tools Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH "NAME"
.sp
atlas\-shell\-tools \-- A command line toolset for Atlas and related projects

.SH "SYNOPSIS"
*

.SH "DESCRIPTION"
The Atlas Shell Tools are a command line toolset for running commands defined
in Atlas and related projects. The main tool for running commands is
\fBash\fR(1), and the installation can be configured with \fBash\-config\fR(1)
and its various subcommands.

.SH "MANUAL PAGES"
.RS 4
\fBash\fR(1)

\fBash\-config\fR(1)

\fBash\-config\-activate\fR(1)

\fBash\-config\-deactivate\fR(1)

\fBash\-config\-install\fR(1)

\fBash\-config\-list\fR(1)

\fBash\-config\-log\fR(1)

\fBash\-config\-reset\fR(1)

\fBash\-config\-sync\fR(1)

\fBash\-config\-uninstall\fR(1)

\fBash\-plumbing\fR(5)

\fBash\-cli\fR(7)

\fBash\-glossary\fR(7)
.RE


.SH "ATLAS SHELL TOOLS"
.sp
Part of the \fBatlas\-shell\-tools\fR(7) suite
