.\"     Title: ash-plumbing
.\"    Author: Lucas Cram
.\"    Source: ash 1.0.0
.\"  Language: English
.\"
.TH "ASH-PLUMBING" "5" "1 December 2018" "ash 1\&.0\&.0" "Atlas Shell Tools Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH "NAME"
.sp
ash-plumbing \-- Details about how Atlas Shell Tools stores program data
