.\"     Title: atlas-config-update
.\"    Author: Lucas Cram
.\"    Source: atlas-shell-tools 0.0.1
.\"  Language: English
.\"
.TH "ATLAS-CONFIG-UPDATE" "1" "1 December 2018" "atlas\-shell\-tools 0\&.0\&.1" "Atlas Shell Tools Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH "NAME"
.sp
atlas\-config\-update \-\- Update the Atlas Shell Tools core toolkit

.SH "SYNOPSIS"
.sp
.nf
\fIatlas\-config\fR \fIupdate\fR \-\-help
\fIatlas\-config\fR \fIupdate\fR
.fi

.SH "DESCRIPTION"
.sp
Update the \fBatlas\-shell\-tools\fR(7) core toolkit using \fBgit\fR(1). This will not
actually update any modules. To update modules using your repos, see
\fBatlas\-config\-repo\fR(1).

.SH "OPTIONS"
.sp
.PP
\fB\-\-help\fR
.RS 4
Show this help menu.
.RE

.SH "SEE ALSO"
.sp
\fBatlas\-config\fR(1), \fBatlas\-config\-repo\fR(1)

.SH "ATLAS SHELL TOOLS"
.sp
Part of the \fBatlas\-shell\-tools\fR(7) suite

