.\"     Title: atlas-plumbing
.\"    Author: Lucas Cram
.\"    Source: atlas-shell-tools 0.0.1
.\"  Language: English
.\"
.TH "ATLAS-PLUMBING" "5" "1 December 2018" "atlas\-shell\-tools 0\&.0\&.1" "Atlas Shell Tools Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH "NAME"
.sp
atlas\-plumbing \-\- Details about how Atlas Shell Tools stores program data

.SH "SYNOPSIS"
$HOME/.local/share/atlas-shell-tools

.SH "DESCRIPTION"
.sp
TODO

.SH "ATLAS SHELL TOOLS"
.sp
Part of the \fBatlas\-shell\-tools\fR(7) suite
