package org.openstreetmap.atlas.geography.atlas.dsl.selection.predicate.chained

import groovy.transform.ToString
import groovy.transform.builder.Builder
import org.openstreetmap.atlas.geography.atlas.dsl.query.ConditionalConstruct
import org.openstreetmap.atlas.geography.atlas.dsl.selection.predicate.BaseContextualPredicate

/**
 * Store the ConditionalConstruct along with the Predicate. The ConditionalConstruct is generated by
 * the Statement's WHERE clause.
 *
 * @author Yazad Khambata
 */
@ToString(includeSuperProperties = true, includePackage = false)
@Builder(includeSuperProperties = true)
class ConditionalConstructPredicate<T> extends BaseContextualPredicate<T> {
    ConditionalConstruct conditionalConstruct
}
