# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
general:
  branches:
    only:
      - main
      - dev
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      # - run: if [ -z "$SONAR_TOKEN" ]; then echo "SONAR_TOKEN missing"; else echo "SONAR_TOKEN is here"; fi
      # - run: echo $SONAR_TOKEN
      # Run jar first, as the checkstyle plugin depends on atlas itself here.
      - run:
          name: Quality checks (No tests)
          command: ./gradlew jar check -x test -x integrationTest
      - run:
          name: Tests
          command: ./gradlew check
          no_output_timeout: 30m
      # - run: .circleci/sonar.sh
      # - run: ./gradlew cleanPyatlas buildPyatlas
