.\"     Title: ash-config-deactivate
.\"    Author: Lucas Cram
.\"    Source: ash-config 1.0.0
.\"  Language: English
.\"
.TH "ASH-CONFIG-DEACTIVATE" "1" "1 December 2018" "ash-config 1\&.0\&.0" "Atlas Shell Tools Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH "NAME"
.sp
ash-config-deactivate \-- Deactivate an installed module

.SH "SYNOPSIS"
.sp
.nf
\fIash-config deactivate\fR [\-\-help]
\fIash-config deactivate\fR <\fImodule\fR>
.fi

.SH "DESCRIPTION"
.sp
Deactivate the provided <\fImodule\fR>. Commands defined in a deactivated module
cannot be run by the \fBash\fR tool until the module is reactivated.
Deactivating a module will also prevent the commands from showing in the
\fBash\fR tool command list.

.SH "OPTIONS"
.sp

.PP
<\fImodule\fR>
.RS 4
This indicates a module. The module should be referred to using its name, as
reported by \fBash-config-list\fR(1).
.RE

.PP
\fB\-\-help\fR
.RS 4
Show this help menu.
.RE

.SH "SEE ALSO"
.sp
\fBash\-config\fR(1), \fBash\-config\-activate\fR(1)

.SH "ASH-CONFIG"
.sp
Part of the \fBash\-config\fR(1) suite

