.\"     Title: ash-config-activate
.\"    Author: Lucas Cram
.\"    Source: ash-config 1.0.0
.\"  Language: English
.\"
.TH "ASH-CONFIG-ACTIVATE" "1" "1 December 2018" "ash-config 1\&.0\&.0" "Atlas Shell Tools Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------

.SH "NAME"
.sp
ash-config-activate \-- Activate an installed module

.SH "SYNOPSIS"
.sp
.nf
\fIash-config activate\fR [\-\-help]
\fIash-config activate\fR <\fImodule\fR>
.fi
