package org.openstreetmap.atlas.proto.converters;

import org.openstreetmap.atlas.exception.CoreException;
import org.openstreetmap.atlas.proto.ProtoIntegerArray;
import org.openstreetmap.atlas.proto.ProtoIntegerArrayOfArrays;
import org.openstreetmap.atlas.utilities.arrays.IntegerArrayOfArrays;
import org.openstreetmap.atlas.utilities.conversion.TwoWayConverter;

import com.google.common.primitives.Ints;

/**
 * Converts between the {@link IntegerArrayOfArrays} and its autogenerated protobuf counterpart.
 *
 * @author lcram
 */
public class ProtoIntegerArrayOfArraysConverter
        implements TwoWayConverter<ProtoIntegerArrayOfArrays, IntegerArrayOfArrays>
{
    @Override
    public ProtoIntegerArrayOfArrays backwardConvert(final IntegerArrayOfArrays array)
    {
        final ProtoIntegerArrayOfArrays.Builder arraysBuilder = ProtoIntegerArrayOfArrays
                .newBuilder();

        for (int index = 0; index < array.size(); index++)
        {
            final ProtoIntegerArray.Builder subArrayBuilder = ProtoIntegerArray.newBuilder();
            final int[] subArray = array.get(index);
            if (subArray == null)
            {
                throw new CoreException("{} cannot convert arrays with null elements",
                        this.getClass().getName());
            }
            for (int subIndex = 0; subIndex < subArray.length; subIndex++)
            {
                subArrayBuilder.addElements(subArray[subIndex]);
            }
            arraysBuilder.addArrays(subArrayBuilder);
        }
        if (array.getName() != null)
        {
            arraysBuilder.setName(array.getName());
        }

        return arraysBuilder.build();
    }

    @Override
    public IntegerArrayOfArrays convert(final ProtoIntegerArrayOfArrays protoArray)
    {
        final IntegerArrayOfArrays integerArrayOfArrays = new IntegerArrayOfArrays(
                protoArray.getArraysCount());
        for (int index = 0; index < protoArray.getArraysCount(); index++)
        {
            final int[] items = Ints.toArray(protoArray.getArrays(index).getElementsList());
            integerArrayOfArrays.add(items);
        }

        if (protoArray.hasName())
        {
            integerArrayOfArrays.setName(protoArray.getName());
        }

        return integerArrayOfArrays;
    }
}
